# Generated by Django 6.0.6 on 2026-06-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
