# Generated by Django 6.0.6 on 2026-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
